### ISSUE TITLE
Documentation Examples Do Not Compile 

### ISSUE THREAD

**Issue by liamtimms** [Enet4/nifti-rs#100]
Hi,

I am interested in testing this crate but when I copy and paste the first example in the documentation, paste directly into a `main.rs` file, I get the following error:

```rust

 1  error: expected item, found keyword `let`
  --> src/main.rs:3:1
   |
 3 | let obj = ReaderOptions::new().read_file("myvolume.nii.gz")?;
   | ^^^ consider using `const` or `static` instead of `let` for global variables

 error: could not compile `nifti-test` due to previous error
```

If I instead wrap the first line in a `main()` function I receive:

```rust
error[E0277]: the `?` operator can only be used in a function that returns `Result` or `Option` (or another type that implements `FromResidual`)
 --> src/main.rs:5:64
  |
3 | fn main() {
  | --------- this function should return `Result` or `Option` to accept `?`
4 |     // let obj = ReaderStreamedOptions::new().read_file("test.nii")?;
5 |     let obj = ReaderOptions::new().read_file("myvolume.nii.gz")?;
  |                                                                ^ cannot use the `?` operator in a function that returns `()`
  |
  = help: the trait `FromResidual<Result<Infallible, NiftiError>>` is not implemented for `()`
```

Since this is my first contact with the package it's unclear how I would go about debugging these issues or what a working example would look like. 

Thanks.

**Comment by Enet4** [comment]
Hello @liamtimms. Those [documentation tests](https://doc.rust-lang.org/rustdoc/write-documentation/documentation-tests.html) are guaranteed to compile, as they are even tested by the compiler. What is happening here is that the tests include hidden boilerplate around the code so that the error may be propagated using the `?` operator.
This is a common pattern of test writing in Rust. You can find more information on this in the Rust book, [chapter 9 on recoverable errors](https://doc.rust-lang.org/stable/book/ch09-02-recoverable-errors-with-result.html), and [chapter 11 on writing tests](https://doc.rust-lang.org/stable/book/ch11-01-writing-tests.html).

For reference, the documented snippet would expand to something like this:

```rust
use nifti::{NiftiObject, ReaderOptions, NiftiVolume};
use nifti::error::Result;

fn main() {
    run().unwrap_or_else(|e| {
        eprintln!("Error! {}", e);
        std::process::exit(-2);
    });
}

fn run() -> Result<(), NiftiError> {
    let obj = ReaderOptions::new()
        .read_file("myvolume.nii.gz")?;
    // use obj
    let header = obj.header();
    let volume = obj.volume();
    let dims = volume.dim();
    Ok(())
}
```

**Comment by liamtimms** [comment]
Got it, thanks, I had encountered/used the `?` operator but hadn't read the section about testing. This was extremely helpful; thank you for your time.
