### ISSUE TITLE
Malformed header writing when `descrip` has a different size

### ISSUE THREAD

**Issue by Enet4** [Enet4/nifti-rs#32]
When writing the header, we are currently writing all bytes of the `descrip` field [here](https://github.com/Enet4/nifti-rs/blob/master/src/writer.rs#L248), but this can make an invalid NifTI file if this vector has a length different from 80 bytes. It's a public field, which means that this can happen in user land.

We can do one of two things to fix this:

-  Make an _a priori_ validation, raise an error if this vector is not 80-lengthed.
-  Or when writing, expand with trailing zeros if it's too short, truncate if it's too large.

CC @nilgoyette

**Comment by nilgoyette** [comment]
I agree with your first point, but I would also do the 'expand' part of your second point.

Too long is indeed a problem. I don't think we should truncate because I would be really surprised if I was a user. We should prefer the least astonishing feature. Too short doesn't seem like a real problem. I think the user should be able to write

    let description = String::from("wathever");
    header.descrip = description.into_bytes();

without worrying about the number of bytes. Or we could offer a `Header::set_description` method if there's a lot of places where it needs to be checked. It's only when writing, right?

**Comment by Enet4** [comment]
Right, we can make it asymmetrical: trailing zeros if it's too short, raise an error if it's too long. While our current stance is to keep all members public and only validate them when required, we can indeed add setter methods to ensure consistency, such as `set_description`.
