### ISSUE TITLE
ndarray 0.13

### ISSUE THREAD

**Issue by nilgoyette** [Enet4/nifti-rs#58]
I tried updating nifti-rs to ndarray 0.13 because we also want to update our enterprise project, but there's a problem. Now that "approx" is a feature flag of ndarray, we need a feature that doesn't exist: [optional `dev-dependencies`](https://github.com/rust-lang/cargo/issues/1596). Without this feature, the "approx" crate will always be included, even in normal builds. I understand that we do not want that, but I don't see what we're supposed to do about it. Nobody's working in cargo issue 1596, so we shouldn't wait. Thoughts?

**Comment by Enet4** [comment]
Unless I overlooked something, yes, we'll have to make do with keeping a partially "dangling" dependency.  The best course of action is to make `approx` a permanent dev dependency once `ndarray` is also updated. Since we rely on this one on our public API, this will be a breaking change that also requires consumers to update ndarray. Can you send in a PR? Thank you very much.

**Comment by nilgoyette** [comment]
Yes, I'm pushing it today. Thank you for your feedback.
